### ISSUE TITLE
Nuget Deadlock

### ISSUE THREAD

**Issue by tweekerz** [tweekerz/PowerShell#6]
Was trying to use the TestHMAEAS script today and it’s failing on the nuget call with a deadlock. 

Here’s the example error where I tried it directly:
Install-Package Microsoft.IdentityModel.Clients.ActiveDirectory -RequiredVersion 3.19.8 -Source 'https://www.nuget.org/api/v2' -Scope CurrentUser

The package(s) come(s) from a package source that is not marked as trusted.
Are you sure you want to install software from 'https://www.nuget.org/api/v2'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): y

Install-Package : Dependency loop detected for package 'Microsoft.IdentityModel.Clients.ActiveDirectory'.

At line:1 char:1
+ Install-Package Microsoft.IdentityModel.Clients.ActiveDirectory -Requ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : Deadlock detected: (Microsoft.Ident...ActiveDirectory:String) [Install-Package], Exception
    + FullyQualifiedErrorId : DependencyLoopDetected,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by tweekerz** [comment]
Workaround introduced today by skipping dependencies.

**Comment by archmangler** [comment]
How do you skip dependencies?
